# ./docker-compose.yml
services:

  postgres:
    image: postgres:14
    container_name: vectoradmin-postgres
    restart: always
    environment:
      POSTGRES_USER: vectoradmin
      POSTGRES_PASSWORD: vectoradmin123
      POSTGRES_DB: vdbms
    ports:
      - "5433:5432"
    volumes:
      - vectoradmin_pgdata:/var/lib/postgresql/data

  chromadb:
    build:
      context: ../chroma # location of local chromadb repo folder
      dockerfile: Dockerfile
    image: custom-chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST_ADDR=0.0.0.0
      - CHROMA_HOST_PORT=8000
      - CHROMA_WORKERS=1
      - CHROMA_LOG_CONFIG=chromadb/log_config.yml
      - CHROMA_TIMEOUT_KEEP_ALIVE=30
      - IS_PERSISTENT=TRUE
      - IS_MULTI_TENANT=FALSE
    restart: always

  vectoradmin:
    image: ghcr.io/mintplex-labs/vector-admin:latest
    container_name: vectoradmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - JWT_SECRET=dev-mode-jwt-secret-keep-out-of-prod
      - INNGEST_EVENT_KEY=background_workers
      - INNGEST_SIGNING_KEY=dev-mode-signing-key
      - INNGEST_LANDING_PAGE=true
      - DB_TYPE=chroma
      - DB_HOST=chromadb
      - DB_PORT=8000
      - DATABASE_CONNECTION_STRING=postgresql://vectoradmin:vectoradmin123@postgres:5432/vdbms
      - DISABLE_TELEMETRY=true
    restart: always

  ingest-runner:
    build:
      context: ./ingest-runner
    container_name: ingest-runner
    volumes:
      - ./shared:/shared
    depends_on:
      - ocr-helper
      - chromadb

  ocr-helper:
    build:
      context: ./ocr-helper
    container_name: ocr-helper
    ports:
      - "8000:8000"
    depends_on:
      - openwebui
    volumes:
      - ./shared:/shared

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    restart: always

  rag-api:
    build:
      context: ./rag-api
    ports:
      - "5050:5050"
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_URL=http://chromadb:8000
    depends_on:
      - chromadb
      - ollama
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY}
      - GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID}
      - GOOGLE_DRIVE_REDIRECT_URI=${GOOGLE_DRIVE_REDIRECT_URI}
    ports:
      - "3000:8080"
    depends_on:
      - ollama
      - chromadb
    volumes:
      - ./rag_tool.py:/app/plugins/rag_tool.py
      - ./rag_tool.json:/app/plugins/rag_tool.json
    restart: always

volumes:
  ollama_models:
  vectoradmin_pgdata: